### ISSUE TITLE
CSS issues in mini-condo form

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Mini-Capstone#177]
These are just suggestions but i think to ensure consistency with the other forms in the website

1) the font color of the input fields should be black (not the labels, the actual user input). Its more easily readable and thats how all other forms in the website are done
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/f4193635-7aba-405e-9aed-bf051498e464)

2) The condo image can be moved to the top of the form and be the first option in the form instead of the last. In the signup page and in the property profile form the image selection is the first thing the user gets in contact with in the form. So i think it would be better to move it up so its the same as the other forms
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/fe1c968c-6203-4cdb-ac91-4a242b2a6934)
 
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/00b10f64-8f07-4f57-a390-38df6507196a)

3) At the top right of the mini condo form, maybe we should include an 'x' button to close the mini condo form? Currently, if the user opens it they have no choice but to fill a condo and click save, but i feel like they should be able to toggle it open close?if they dont want to add one they shouldnt be forced as they can add one later.  The logistics of this can be discussed as a team
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/3653f8d9-10fb-4980-98e7-583dd4d17d98)

4) save condo button does not have the same onhover styling as all of the other buttons in the website. This is the same for the delete button. The delete button should also have an onhover effect.
https://www.loom.com/share/60e1ee7278c84a65b7f7512e4422e8b0

**Comment by Dom-Isbis** [comment]
I agree with all these suggestions. Would allow all our forms to be more consistent.

**Comment by layanat** [comment]
this is not the final version of the form, as it will be refactored in the next sprint. When We do, we can discuss CSS styling and get back to resolving these issues
