### ISSUE TITLE
condo management component UI bug

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Mini-Capstone#181]
using the mini-condo form.... if the user only enters the unit number it affects teh UI of teh component and makes theh buttons appear on the left side of the page ,when they are meant to appear on the right side
I think, maybe the easiest fix for this is to just make all fields (Except the condo image) mandatory in the mini condo form

![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/5bd6ef54-a356-48ab-8b72-99cebcb18fc8)

**Comment by laurenrigante** [comment]
i think the issue with this is that the fields are only being rendered if there is vlues in them, but i think the fields shuld be rendered regardless and just be empty if necessary. that way, the structure of the component stays the same no matter what? Let me know what u  think

**Comment by layanat** [comment]
yeah i think that would fix it! I will look into it
