### ISSUE TITLE
Invalid success toast 

### ISSUE THREAD

**Issue by Dom-Isbis** [leobrod44/Mini-Capstone#265]
Success toast is displayed even when backend errors occur and request is ultimately not submitted. 
https://www.loom.com/share/c26a7c68ac5c49c8a09b96cd77d38c3b

<img width="826" alt="Screenshot 2024-03-20 at 3 54 30 PM" src="https://github.com/leobrod44/Mini-Capstone/assets/97750045/f0726c5f-97a1-49d4-99f5-ada2dc9b1aff">

**Comment by leobrod44** [comment]
This bug is missing SEVERITY: x/5
