### ISSUE TITLE
BUG: condo id is being displayed on condo component

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Mini-Capstone#333]
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/3194220d-d2e1-485a-ab05-32b548a6932e)

severity is high since this was merged to main

Severity :5/5

**Comment by leobrod44** [comment]
has this been fixed?

**Comment by altam-sh** [comment]
It looks like this only happens when you're signed in as Owner/Renter
