### ISSUE TITLE
No sign up option when loging out using logout via Logout button

### ISSUE THREAD

**Issue by leobrod44** [leobrod44/Mini-Capstone#80]
![image](https://github.com/leobrod44/Mini-Capstone/assets/65002959/0a5e401f-7d8c-4cb4-a312-059de31e0301)

**Comment by mattflahertyy** [comment]
in navbar replace "navigate("/login");" in the logout method:

  const logout = async (e) => {
    e.preventDefault();
    store.remove("user");
    store.remove("role");
    navigate("/login");
  };

with: window.location.href = '/';
